//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.05 at 10:33:51 AM CST 
//


package nbi.xsd.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FileDetailRecordType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FileDetailRecordType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pattern" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="remoteFolderName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="localFolderName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomLogicClassName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="putOrGet" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="bulkTransport" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="compressPut" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FileDetailRecordType", propOrder = {
    "pattern",
    "remoteFolderName",
    "localFolderName",
    "customLogicClassName",
    "putOrGet",
    "bulkTransport",
    "compressPut"
})
public class FileDetailRecordType {

    @XmlElement(required = true)
    protected String pattern;
    @XmlElement(required = true)
    protected String remoteFolderName;
    @XmlElement(required = true)
    protected String localFolderName;
    @XmlElementRef(name = "CustomLogicClassName", type = JAXBElement.class)
    protected JAXBElement<String> customLogicClassName;
    protected boolean putOrGet;
    protected boolean bulkTransport;
    protected boolean compressPut;
    @XmlAttribute(name = "description")
    protected String description;

    /**
     * Gets the value of the pattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPattern() {
        return pattern;
    }

    /**
     * Sets the value of the pattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPattern(String value) {
        this.pattern = value;
    }

    /**
     * Gets the value of the remoteFolderName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemoteFolderName() {
        return remoteFolderName;
    }

    /**
     * Sets the value of the remoteFolderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemoteFolderName(String value) {
        this.remoteFolderName = value;
    }

    /**
     * Gets the value of the localFolderName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalFolderName() {
        return localFolderName;
    }

    /**
     * Sets the value of the localFolderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalFolderName(String value) {
        this.localFolderName = value;
    }

    /**
     * Gets the value of the customLogicClassName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCustomLogicClassName() {
        return customLogicClassName;
    }

    /**
     * Sets the value of the customLogicClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCustomLogicClassName(JAXBElement<String> value) {
        this.customLogicClassName = value;
    }

    /**
     * Gets the value of the putOrGet property.
     * 
     */
    public boolean isPutOrGet() {
        return putOrGet;
    }

    /**
     * Sets the value of the putOrGet property.
     * 
     */
    public void setPutOrGet(boolean value) {
        this.putOrGet = value;
    }

    /**
     * Gets the value of the bulkTransport property.
     * 
     */
    public boolean isBulkTransport() {
        return bulkTransport;
    }

    /**
     * Sets the value of the bulkTransport property.
     * 
     */
    public void setBulkTransport(boolean value) {
        this.bulkTransport = value;
    }

    /**
     * Gets the value of the compressPut property.
     * 
     */
    public boolean isCompressPut() {
        return compressPut;
    }

    /**
     * Sets the value of the compressPut property.
     * 
     */
    public void setCompressPut(boolean value) {
        this.compressPut = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

}
