//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.05 at 10:33:51 AM CST 
//


package nbi.xsd.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nbi.xsd.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FileDetailRecordTypeCustomLogicClassName_QNAME = new QName("", "CustomLogicClassName");
    private final static QName _Server_QNAME = new QName("", "server");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nbi.xsd.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Servers }
     * 
     */
    public Servers createServers() {
        return new Servers();
    }

    /**
     * Create an instance of {@link ServerType }
     * 
     */
    public ServerType createServerType() {
        return new ServerType();
    }

    /**
     * Create an instance of {@link FileDetailRecordType }
     * 
     */
    public FileDetailRecordType createFileDetailRecordType() {
        return new FileDetailRecordType();
    }

    /**
     * Create an instance of {@link FilePatternType }
     * 
     */
    public FilePatternType createFilePatternType() {
        return new FilePatternType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CustomLogicClassName", scope = FileDetailRecordType.class)
    public JAXBElement<String> createFileDetailRecordTypeCustomLogicClassName(String value) {
        return new JAXBElement<String>(_FileDetailRecordTypeCustomLogicClassName_QNAME, String.class, FileDetailRecordType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServerType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "server")
    public JAXBElement<ServerType> createServer(ServerType value) {
        return new JAXBElement<ServerType>(_Server_QNAME, ServerType.class, null, value);
    }

}
